@extends('layouts.header')
@section('content')
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-left">
        <li> <a href="">Generated Records</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <p>{{Auth::user()->name}}
                    <i class='pe-7s-user'></i>
                    <b class="caret"></b>
                </p>
            </a>
            <ul class="dropdown-menu">
                <li><a  data-toggle="modal" data-target="#profile" data-toggle="profle" >Change Password</a></li>
            </ul>
        </li>
    </ul>
</div>
</div>
</nav>
@if(session()->has('status'))
    <div class="alert alert-success fade in col-md-6" style='margin-bottom:10px;margin-top:10px;'>
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>  {{session()->get('status')}}</strong>
    </div>
    @endif
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                
                <div class="card">
                    <div class="content table-responsive table-full-width">
                        <form method="GET" action="" class="custom_form" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-md-7">
                                   
                                </div>
                                <div class="col-md-3">
                                    {{-- <input type='text' class='form-control' name='name' placeholder="Search" required> --}}
                                    <select class='form-control' name='company' placeholder="Search" required>
                                        <option value='All'>Select Company</option>
                                        @foreach($companies as $company)
                                            <option value='{{$company->id}}' {{ ($company->id == $comp) ? 'selected="selected"' : '' }}  >{{$company->company_name}}</option>
                                        @endforeach
                                </select>
                                </div>
                                <div class="col-md-2">
                                    <button class="btn btn-primary btn-md btn-submit" style="width:100px;border-radius:4px" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                        <table id="generated_reports"  class="table table-striped table-bordered" style="width:100%;">
                            <thead>
                                <tr>
                                    <th>Reference Number</th>
                                    <th>Agency</th>
                                    <th>Company</th>
                                    <th>Location </th>
                                    <th>Positon</th>
                                    <th>Generated By</th>
                                    <th>Period</th>
                                    <th>Date Generated</th>
                                    <th>Remarks</th>
                                    <th>Action </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($generates as $generate)
                                @php
                                $length = strlen($generate->reference_id);
                                if($length == 1)
                                {
                                    $reference_id = "00".$generate->reference_id;
                                }
                                elseif($length == 2)
                                {
                                    $reference_id = "0".$generate->reference_id;
                                }
                                else
                                {
                                    $reference_id = $generate->reference_id;
                                }
                                @endphp
                                <tr>
                                    <td>{{$generate['companyName']->company_name.'-'.date('Y',strtotime($generate->date_from)).'-'.$reference_id}}</td>
                                    <td>{{$generate['AgencyInfo']->agency_name}}</td>
                                    <td>{{$generate['companyName']->company_name}}</td>
                                    <td>{{$generate['locationInfo']->name}}</td>
                                    <td>{{$generate['PositionInfo']->work_name}}</td>
                                    <td>{{$generate['userInfo']->name}}</td>
                                    <td>{{date('M. d, Y',strtotime($generate->date_from)).' - '.date('M. d, Y',strtotime($generate->date_to))}}</td>
                                    <td>{{date('M. d, Y',strtotime($generate->created_at))}}</td>
                                    <td>{!! nl2br(e($generate->remarks)) !!}</td>
                                    <td>
                                        <a href='{{ url('/print-ap?date_from='.$generate->date_from.'&date_to='.$generate->date_to.'&agency='.$generate->agency_id.'&company='.$generate->company_id.'&location='.$generate->location_id.'&position='.$generate->position_id) }}' target='_' style='margin:5px;' class="btn btn-info">&#128438; PRINT</a> <br>
                                        @if(auth()->user()->generate_role == 1)<a href="#edit_remarks{{$generate->id}}"  class='btn btn-success' data-toggle="modal" >Remarks</a>@endif
                                    </td>
                                </tr>
                                @include('edit_remarks')
                                @endforeach
                            </tbody>
                        </table>
                        {{ $generates->appends(['company' => $comp ])->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


